### ISSUE TITLE
Provider status not associated with a course

### ISSUE THREAD

**Issue by sfairty** [paddlesports-north-america/pna-site#41]
The awards of any Provider status, Course Tutor or Course Director are not associated with any course.  Those awards are achieved through a mentored process and logbook.

Currently I cannot give someone their Provider status without creating a course.  Is it possible to eliminate that requirement for the above roles?

**Comment by rkitts** [comment]
I don't believe there is a requirement for a Qualification to refer to a course. However there was a bug in that prevented the creation of Qualifications which I believe is now resolved. Please take a look here:

https://pna-dev-pr-42.herokuapp.com/admin

and see if this is working as you expect. If so I'll push the change to production.

**Comment by sfairty** [comment]
Still getting an "oops" error message.

As an example, I'm trying to give John Carmody his Level 1 Tutor status and
it throws that error.

-Scott

**Comment by rkitts** [comment]
Hmm. If you look here:

https://pna-dev-pr-42.herokuapp.com/admin/members/2

you should see that I was able to give John his Level 1 Tutor qualification. Did you actually try to do this via the test site link given above?

The steps I took were:

Go to Johns member page
Select 'Manage Qualifications'
Select 'New Qualification'
Select 'Level 1 Tutor' from the Award drop down.
Select a date for 'First awarded on'
Select a date for 'Most recent award'
Select 'Create Qualification'

Does that match the steps you took?
